batch_size: 128
temporal_window_size: 16
temporal_downsampling: 5
image_size: 224
learning_rate: 0.1
x3d_num_groups: 1
x3d_width_per_group: 64
x3d_width_factor: 2.0
x3d_depth_factor: 2.2
x3d_bottleneck_factor: 2.25
x3d_conv1_dim: 12
x3d_conv5_dim: 2048
x3d_use_channelwise_3x3x3: 1
x3d_dropout_rate: 0.5
x3d_head_activation: "softmax"
x3d_head_batchnorm: 0
x3d_fc_std_init: 0.01
x3d_final_batchnorm_zero_init: 1