TRAIN:
    model: resnetv2sn101
    workers: 3
    batch_size: 256
    epochs: 120

    lr_mode : cosine
    base_lr: 0.1
    warmup_epochs: 5
    warmup_lr: 0.0
    targetlr : 0.0

    momentum: 0.9
    weight_decay: 0.0001

    using_moving_average : True
    using_bn: True

    print_freq: 100
    model_dir: checkpoint/resnetv2sn101_cosine

    train_root: data/imagenet/train
    train_source: data/imagenet/train.txt
    val_root: data/imagenet/val
    val_source: data/imagenet/val.txt

TEST:
    checkpoint_path : data/pretrained_model/ResNet101v2+SN(8,32).pth
